**WORLD HAPPINESS**

***Nettoyage des données***

1 - Premier apercu des données

In [ ]:
import pandas as pd
from pathlib import Path

files = list(Path("../data").rglob("*.csv"))

# aperçu rapide de tous les fichiers
for f in files:
    df = pd.read_csv(f, sep=None, engine="python", on_bad_lines="skip", encoding="utf-8")
    print(f"{f.name}")
    print(f"{df.shape[0]} lignes x {df.shape[1]} colonnes")
    print("Colonnes :", list(df.columns))
    display(df.head(3))

world_happiness_2015_corrigé.csv
158 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Switzerland,Western Europe,"7,59","8,26","0,96",73,"0,99","0,37","0,24"
1,2,Iceland,Western Europe,"7,56","7,7",1,73,"0,94","0,55","0,74"
2,3,Denmark,Western Europe,"7,53","7,84","0,97",70,"0,97","0,43","0,12"

world_happiness_2016_corrigé.csv
157 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,111,Sierra Leone,Sub-Saharan Africa,"4,635","9,44368","0,53074",44,"0,50429","0,29153","0,16223"
1,144,Chad,Sub-Saharan Africa,"3,763","9,42133","0,53393",46,"0,21048","0,22772","0,09803"
2,139,Ivory Coast,Sub-Saharan Africa,"3,916","9,97862","0,48659",46,"0,66827","0,24811","0,30739"

world_happiness_2017_corrigé.csv
155 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,3,Iceland,Western Europe,"7,504","7,91458",1,71,"0,95277","0,56742","0,33066"
1,15,Ireland,Western Europe,"6,977","8,20897","0,9675",71,"0,87066","0,51053","0,64265"
2,2,Denmark,Western Europe,"7,522","7,92394","0,96309",70,"0,95102","0,42392","0,86316"

world_happiness_2018_corrigé.csv
155 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,145,Afghanistan,South Asia,"3,6315","2,01215","0,20121",59,"0,11671","0,31964","0,07937"
1,112,Albania,Central and Eastern Europe,"4,586","5,55338","0,55534",70,"0,57789","0,2497","0,07098"
2,84,Argelia,Middle East and North Africa,"5,2946","5,93587","0,59359",68,"0,10667","0,09237","0,29437"

world_happiness_2019_corrigé.csv
155 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,"7,7689","7,95824","0,9776",76,"0,944","0,26989","0,86796"
1,2,Denmark,Western Europe,"7,6001","8,21474","0,96855",76,"0,93839","0,44593","0,90675"
2,3,Norway,Western Europe,"7,5539","8,83423","0,97407",77,"0,95605","0,47948","0,75302"

world_happiness_2020_corrigé.csv
152 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,"7,8087","8,36344","0,96896",72,"0,95535","0,28022","0,10373"
1,2,Denmark,Western Europe,"7,6456","8,63519","0,97149",72,"0,95928","0,42609","0,07109"
2,3,Switzerland,Western Europe,"7,5599","9,05054","0,95143",74,"0,90723","0,47218","0,23486"

world_happiness_2021_corrigé.csv
148 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,149,Afghanistan,South Asia,"2,5229","2,11402",0,52,0,"0,22474","0,9825"
1,93,Albania,Central and Eastern Europe,"5,1174","5,7574","0,45126",69,"0,68576","0,31123","0,95529"
2,109,Argelia,Sub-Saharan Africa,"4,8871","5,40196","0,65216",66,"0,1665","0,26656","0,78135"

world_happiness_2022_corrigé.csv
145 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,146,Afghanistan,South Asia,"2,4038","3,43077",0,65,0,"0,18993","0,00832"
1,90,Albania,Central and Eastern Europe,"5,1988","6,51098","0,48923",78,"0,69039","0,29574","0,04836"
2,96,Argelia,Sub-Saharan Africa,"5,1223","6,16812","0,73461",76,"0,19727","0,22752","0,25535"

world_happiness_2023_corrigé.csv
137 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,"7,8042","8,58486","0,97853",71.0,1,"0,29969","0,04551"
1,2,Denmark,Western Europe,"7,5864","8,86229","0,95567",71.0,"0,95192","0,49451","0,06348"
2,3,Iceland,Western Europe,"7,5296","8,75364",1,72.0,"0,95678","0,59219","0,66635"

world_happiness_2024_corrigé.csv
140 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Ladder score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Ladder score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,140,Afghanistan,South Asia,"1,721","2,93451",0,62,0,"0,22638","0,15383"
1,86,Albania,Central and Eastern Europe,"5,3042","6,71748","0,57133",74,"0,79892","0,34403","0,08517"
2,84,Argelia,Sub-Saharan Africa,"5,3635","6,18327","0,73652",72,"0,28611","0,22771","0,34775"

world_happiness_combined_corrigé.csv
1210 lignes x 11 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Year']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,1,Switzerland,Western Europe,"7,58700","8,26132","0,96240",73,"0,99379","0,37289","0,23941",2015
1,2,Iceland,Western Europe,"7,56100","7,70416","1,00000",73,"0,93884","0,54819","0,74371",2015
2,3,Denmark,Western Europe,"7,52700","7,84114","0,97030",70,"0,96962","0,42894","0,12382",2015

world_happiness_2015.csv
158 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Switzerland,Western Europe,"7,59","8,26","0,96",73,"0,99","0,37","0,24"
1,2,Iceland,Western Europe,"7,56","7,7",1,73,"0,94","0,55","0,74"
2,3,Denmark,Western Europe,"7,53","7,84","0,97",70,"0,97","0,43","0,12"

world_happiness_2016.csv
157 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,111,Sierra Leone,Sub-Saharan Africa,"4,635","9,44368","0,53074",44,"0,50429","0,29153","0,16223"
1,144,Chad,Sub-Saharan Africa,"3,763","9,42133","0,53393",46,"0,21048","0,22772","0,09803"
2,139,Ivory Coast,Sub-Saharan Africa,"3,916","9,97862","0,48659",46,"0,66827","0,24811","0,30739"

world_happiness_2017.csv
155 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,3,Iceland,Western Europe,"7,504","7,91458",1,71,"0,95277","0,56742","0,33066"
1,15,Ireland,Western Europe,"6,977","8,20897","0,9675",71,"0,87066","0,51053","0,64265"
2,2,Denmark,Western Europe,"7,522","7,92394","0,96309",70,"0,95102","0,42392","0,86316"

world_happiness_2018.csv
155 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,145,Afghanistan,South Asia,"3,6315","2,01215","0,20121",59,"0,11671","0,31964","0,07937"
1,112,Albania,Central and Eastern Europe,"4,586","5,55338","0,55534",70,"0,57789","0,2497","0,07098"
2,84,Argelia,Middle East and North Africa,"5,2946","5,93587","0,59359",68,"0,10667","0,09237","0,29437"

world_happiness_2019.csv
155 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,"7,7689","7,95824","0,9776",76,"0,944","0,26989","0,86796"
1,2,Denmark,Western Europe,"7,6001","8,21474","0,96855",76,"0,93839","0,44593","0,90675"
2,3,Norway,Western Europe,"7,5539","8,83423","0,97407",77,"0,95605","0,47948","0,75302"

world_happiness_2020.csv
152 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,"7,8087","8,36344","0,96896",72,"0,95535","0,28022","0,10373"
1,2,Denmark,Western Europe,"7,6456","8,63519","0,97149",72,"0,95928","0,42609","0,07109"
2,3,Switzerland,Western Europe,"7,5599","9,05054","0,95143",74,"0,90723","0,47218","0,23486"

world_happiness_2021.csv
148 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,149,Afghanistan,South Asia,"2,5229","2,11402",0,52,0,"0,22474","0,9825"
1,93,Albania,Central and Eastern Europe,"5,1174","5,7574","0,45126",69,"0,68576","0,31123","0,95529"
2,109,Argelia,Sub-Saharan Africa,"4,8871","5,40196","0,65216",66,"0,1665","0,26656","0,78135"

world_happiness_2022.csv
145 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,146,Afghanistan,South Asia,"2,4038","3,43077",0,65,0,"0,18993","0,00832"
1,90,Albania,Central and Eastern Europe,"5,1988","6,51098","0,48923",78,"0,69039","0,29574","0,04836"
2,96,Argelia,Sub-Saharan Africa,"5,1223","6,16812","0,73461",76,"0,19727","0,22752","0,25535"

world_happiness_2023.csv
137 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,"7,8042","8,58486","0,97853",71.0,1,"0,29969","0,04551"
1,2,Denmark,Western Europe,"7,5864","8,86229","0,95567",71.0,"0,95192","0,49451","0,06348"
2,3,Iceland,Western Europe,"7,5296","8,75364",1,72.0,"0,95678","0,59219","0,66635"

world_happiness_2024.csv
140 lignes x 10 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Ladder score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

,Ranking,Country,Regional indicator,Ladder score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,140,Afghanistan,South Asia,"1,721","2,93451",0,62,0,"0,22638","0,15383"
1,86,Albania,Central and Eastern Europe,"5,3042","6,71748","0,57133",74,"0,79892","0,34403","0,08517"
2,84,Argelia,Sub-Saharan Africa,"5,3635","6,18327","0,73652",72,"0,28611","0,22771","0,34775"

world_happiness_combined.csv
1502 lignes x 11 colonnes
Colonnes : ['Ranking', 'Country', 'Regional indicator', 'Happiness score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Year']

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,1,Switzerland,Western Europe,"7,58700","8,26132","0,96240",73,"0,99379","0,37289","0,23941",2015
1,2,Iceland,Western Europe,"7,56100","7,70416","1,00000",73,"0,93884","0,54819","0,74371",2015
2,3,Denmark,Western Europe,"7,52700","7,84114","0,97030",70,"0,96962","0,42894","0,12382",2015

On voit que 'world_happiness_combined.csv' possède une variable en plus, 'Year'. Cela permet de retrouver les données brut de la décennie dans un même csv

2. Les valeurs manquantes

In [3]:
import pandas as pd

for f in files:
    df = pd.read_csv(f, sep=None, engine="python", on_bad_lines="skip", encoding="utf-8")
    
    for col in df.columns:
        missing_idx = df[df[col].isna()].index.tolist()
        if missing_idx:
            print(f"{f.name}")
            print(f"- {col} : index {missing_idx}\n")

world_happiness_2017.csv
- Regional indicator : index [79]

world_happiness_2019.csv
- Regional indicator : index [48, 118]

world_happiness_2023.csv
- Healthy life expectancy : index [98]

world_happiness_combined.csv
- Regional indicator : index [394, 673, 743]

Les valeurs manquantes sont peu nombreuses :
- 1 * 'Regional indicator' de 'world_happiness_2017.csv'
- 2 * 'Regional indicator' de 'world_happiness_2019.csv'
- 1 * 'Healthy life expectancy' de 'world_happiness_2023.csv'

On retrouve bien les valeurs manquantes de la variable 'Regional indicator' dans 'world_happiness_combined.csv', 

mais pas celle de la variable 'Healthy life expectancy' de 'world_happiness_2023.csv'

In [4]:
for f in files:
    df = pd.read_csv(f, sep=None, engine="python", on_bad_lines="skip", encoding="utf-8")
    
    missing_rows = df[df.isna().any(axis=1)]
    
    if missing_rows.empty:
        pass
    else:
        print(f"{f.name}")
        print(f"{len(missing_rows)} valeur(s) manquante(s) :")
        display(missing_rows)

world_happiness_2017.csv
1 valeur(s) manquante(s) :

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
79,87,Greece,NaN,"5,227","6,89283","0,76955",71,"0,14543",0,"0,09324"

world_happiness_2019.csv
2 valeur(s) manquante(s) :

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
48,49,Cyprus,NaN,"6,0458","7,50051","0,75329",77,"0,64287","0,33664","0,08973"
118,120,Gambia,NaN,"4,5163","1,82777","0,57836",66,"0,60555","0,47478","0,3692"

world_happiness_2023.csv
1 valeur(s) manquante(s) :

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
98,99,State of Palestine,Middle East and North Africa,"4,9078","5,20061","0,80811",NaN,"0,53963","0,15516","0,88085"

world_happiness_combined.csv
3 valeur(s) manquante(s) :

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
394,87,Greece,NaN,"5,22700","6,89283","0,76955",71,"0,14543","0,00000","0,09324",2017
673,49,Cyprus,NaN,"6,04580","7,50051","0,75329",77,"0,64287","0,33664","0,08973",2019
743,120,Gambia,NaN,"4,51630","1,82777","0,57836",66,"0,60555","0,47478","0,36920",2019

La valeur manquante de la variable 'Healthy life expectancy' pour le pays Palestine a été corrigé dans 'world_happiness_combined.csv'

Il ne reste qu'à renseigner la variable 'Regional indicator' pour les pays Greece, Cyprus et Gambia, en observant leur précedent affectation :
- Greece : Middle East and North Africa
- Cyprus : Western Europe
- Gambia : Sub-Saharan Africa

3. Correction des valeurs manquantes

In [16]:
import pandas as pd
import os

raw_dossier = "../data/raw"
output_dossier = "../data/corrigé"

region_corrections = {
    "Greece": "Middle East and North Africa",
    "Cyprus": "Western Europe",
    "Gambia": "Sub-Saharan Africa"
}

health_corrections = {
    "State of Palestine": 39  
}

for filename in os.listdir(raw_dossier):
    if filename.endswith(".csv"):
        filepath = os.path.join(raw_dossier, filename)
        df = pd.read_csv(filepath, sep=None, engine="python", on_bad_lines="skip", encoding="utf-8")

        missing_before = df.isna().sum().sum()

        # Correction Regional indicator
        if "Regional indicator" in df.columns:
            for country, region in region_corrections.items():
                mask = (df["Country"] == country) & (df["Regional indicator"].isna())
                df.loc[mask, "Regional indicator"] = region

        # Correction Healthy life expectancy
        if "Healthy life expectancy" in df.columns:
            for country, value in health_corrections.items():
                mask = (df["Country"] == country) & (df["Healthy life expectancy"].isna())
                df.loc[mask, "Healthy life expectancy"] = value

        # Vérif après correction
        missing_after = df.isna().sum().sum()
        print(f"Traitement de {filename} ")
        print(f"Valeurs manquantes avant correction : {missing_before}")
        print(f"Valeurs manquantes après correction : {missing_after}")

        output_path = os.path.join(output_dossier, filename.replace(".csv", "_corrigé.csv"))
        df.to_csv(output_path, index=False, encoding="utf-8")
        print(f"Fichier corrigé enregistré : {output_path}\n")

Traitement de world_happiness_2015.csv
Valeurs manquantes avant correction : 0
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2015_corrigé.csv

Traitement de world_happiness_2016.csv
Valeurs manquantes avant correction : 0
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2016_corrigé.csv

Traitement de world_happiness_2017.csv
Valeurs manquantes avant correction : 1
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2017_corrigé.csv

Traitement de world_happiness_2018.csv
Valeurs manquantes avant correction : 0
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2018_corrigé.csv

Traitement de world_happiness_2019.csv
Valeurs manquantes avant correction : 2
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2019_corrigé.csv

Traitement de world_happiness_2020.csv
Valeurs manquantes avant correction : 0
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2020_corrigé.csv

Traitement de world_happiness_2021.csv
Valeurs manquantes avant correction : 0
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2021_corrigé.csv

Traitement de world_happiness_2022.csv
Valeurs manquantes avant correction : 0
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2022_corrigé.csv

Traitement de world_happiness_2023.csv
Valeurs manquantes avant correction : 1
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2023_corrigé.csv

Traitement de world_happiness_2024.csv
Valeurs manquantes avant correction : 0
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_2024_corrigé.csv

Traitement de world_happiness_combined.csv
Valeurs manquantes avant correction : 3
Valeurs manquantes après correction : 0
Fichier corrigé enregistré : ../data/corrigé\world_happiness_combined_corrigé.csv

4. Nombre de pays par années

In [10]:
combined_path = "../data/corrigé/world_happiness_combined_corrigé.csv"

df_combined = pd.read_csv(combined_path, encoding="utf-8")

countries_year = df_combined.groupby("Year")["Country"].nunique()
print("Nombre de pays par année :\n", countries_year)

countries_all_years = (
    df_combined.groupby("Country")["Year"]
    .nunique()
    .reset_index()
)
max_years = df_combined["Year"].nunique()
countries_all_years = countries_all_years[countries_all_years["Year"] == max_years]["Country"].tolist()

print(f"\n Seul {len(countries_all_years)} pays apparaissent chaque année ({max_years} années au total).")

Nombre de pays par année :
 Year
2015    158
2016    157
2017    155
2018    155
2019    155
2020    152
2021    148
2022    145
2023    137
2024    140
Name: Country, dtype: int64

 Seul 121 pays apparaissent chaque année (10 années au total).

Le nombre de pays n'est pas égale pour chaque année.

On peut, après vérification, garder pour le fichier 'world_happiness_combined', que les pays qui apparaissent chaque année seront gardés.

5. Affichage des pays apparraissant dans les données

In [ ]:
pays_uniques = sorted(df["Country"].dropna().unique().tolist())

# Regroupe par pays et calcule :
# - le nombre d'occurrences
# - la liste des années correspondantes
resume_pays = (
    df_combined.groupby("Country")["Year"]
    .agg(["count", lambda x: sorted(x.unique().tolist())])
    .reset_index()
    .rename(columns={"count": "Nb_occurrences", "<lambda_0>": "Annees"})
)

resume_pays = resume_pays.sort_values(by="Nb_occurrences", ascending=False)

print("Nombre d'occurrences et années par pays :\n")
print(resume_pays.to_string(index=False))

Nombre d'occurrences et années par pays :

                  Country  Nb_occurrences                                                       Annees
              Afghanistan              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Albania              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Armenia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Argentina              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Belgium              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Austria              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Australia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Bangladesh              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
             Burkina Faso              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Brazil              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Bulgaria              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Botswana              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
   Bosnia and Herzegovina              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Bolivia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Benin              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
              El Salvador              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Ecuador              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Egypt              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Costa Rica              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
       Dominican Republic              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Denmark              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Cyprus              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Cambodia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    China              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Cameroon              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Canada              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                     Chad              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Chile              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Croatia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Colombia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Japan              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Hungary              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Iceland              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    India              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Indonesia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Guatemala              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Greece              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Honduras              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Guinea              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Germany              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Ghana              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Gabon              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Georgia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   France              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Finland              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Ethiopia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Estonia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Zimbabwe              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Venezuela              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Uzbekistan              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
           United Kingdom              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Uganda              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Ukraine              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
     United Arab Emirates              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Tunisia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Vietnam              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Zambia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                     Togo              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Thailand              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Tanzania              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
             Saudi Arabia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Russia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Romania              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Spain              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Italy              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
              Ivory Coast              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Jamaica              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                     Iraq              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                     Iran              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Ireland              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Israel              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Kazakhstan              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Jordan              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Kenya              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Liberia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Latvia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Lebanon              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Kyrgyzstan              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Kosovo              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Morocco              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Myanmar              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
              Netherlands              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Nepal              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
              New Zealand              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Malawi              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Luxembourg              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Lithuania              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Malaysia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Madagascar              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Moldova              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Mexico              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Mauritius              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Mauritania              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Malta              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                     Mali              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Mongolia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Nicaragua              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Montenegro              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Senegal              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
             Sierra Leone              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Serbia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Portugal              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Poland              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Panama              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Paraguay              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                     Peru              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
              Philippines              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Norway              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Pakistan              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Nigeria              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Niger              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                   Sweden              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Slovenia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
              South Korea              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
             South Africa              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Singapore              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                 Slovakia              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Uruguay              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
            United States              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                Sri Lanka              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
              Switzerland              10 [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                    Yemen               9       [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2024]
                    Libya               9       [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2024]
                     Laos               9       [2015, 2016, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Namibia               9       [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
               Azerbaijan               9       [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2024]
      Congo (Brazzaville)               9       [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2023, 2024]
                  Bahrain               9       [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
               Tajikistan               9       [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
                   Kuwait               9       [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2024]
               Mozambique               9       [2015, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
             Turkmenistan               8             [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
                   Turkey               8             [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
  Palestinian Territories               8             [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
                   Rwanda               8             [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
                  Belarus               8             [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
         Congo (Kinshasa)               8             [2015, 2016, 2017, 2018, 2019, 2020, 2023, 2024]
                  Comoros               8             [2015, 2016, 2019, 2020, 2021, 2022, 2023, 2024]
                  Argelia               8             [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                  Lesotho               8             [2015, 2017, 2018, 2019, 2020, 2021, 2022, 2024]
                  Burundi               7                   [2015, 2016, 2017, 2018, 2019, 2020, 2021]
           Czech Republic               7                   [2015, 2016, 2017, 2018, 2019, 2020, 2021]
                    Haiti               7                   [2015, 2016, 2017, 2018, 2019, 2020, 2021]
                   Gambia               6                         [2019, 2020, 2021, 2022, 2023, 2024]
                Hong Kong               6                         [2015, 2016, 2018, 2019, 2022, 2024]
 Taiwan Province of China               6                         [2017, 2020, 2021, 2022, 2023, 2024]
                Macedonia               6                         [2015, 2016, 2017, 2018, 2019, 2020]
      Trinidad and Tobago               5                               [2015, 2016, 2017, 2019, 2020]
                    Syria               5                               [2015, 2016, 2017, 2018, 2019]
                   Bhutan               5                               [2015, 2016, 2017, 2018, 2019]
 Central African Republic               5                               [2015, 2017, 2018, 2019, 2020]
              South Sudan               5                               [2016, 2017, 2018, 2019, 2020]
                    Qatar               5                               [2015, 2016, 2017, 2018, 2019]
          North Macedonia               4                                     [2021, 2022, 2023, 2024]
                  Somalia               4                                     [2016, 2017, 2018, 2019]
                    Sudan               4                                     [2015, 2016, 2017, 2018]
                   Angola               4                                     [2015, 2016, 2017, 2018]
Hong Kong S.A.R. of China               4                                     [2017, 2020, 2021, 2023]
                Swaziland               4                                     [2015, 2019, 2020, 2021]
                   Taiwan               4                                     [2015, 2016, 2018, 2019]
                   Belize               3                                           [2016, 2017, 2018]
             North Cyprus               3                                           [2015, 2016, 2017]
                  Czechia               3                                           [2022, 2023, 2024]
                 Maldives               2                                                 [2020, 2021]
                 Suriname               2                                                 [2015, 2016]
                  Algeria               2                                                 [2015, 2016]
                 Eswatini               2                                                 [2022, 2024]
        Somaliland region               2                                                 [2015, 2016]
                  Turkiye               2                                                 [2023, 2024]
                 Djibouti               1                                                       [2015]
                    Congo               1                                                       [2022]
                     Oman               1                                                       [2015]
              Puerto Rico               1                                                       [2016]
        Trinidad & Tobago               1                                                       [2018]
       State of Palestine               1                                                       [2023]

6. Problèmes rencontrés

changement de nom à travers la decennie du à des conflit mondiaux ou choix du peuple 

pays non present sur la totalité de la décennie

cas particulier : Congo 

apparrait sous 3 noms : 
- Congo (Brazzaville) : apparait 9* en [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2023, 2024]
- Congo (Kinshasa) : apparait 8* en [2015, 2016, 2017, 2018, 2019, 2020, 2023, 2024]
- et Congo : apparait 1* en [2022]

les données du Congo en 2022 sont à placer avec les données de Congo (Brazzaville) ou de Congo (Kinshasa) ? sachant que ces deux pays non pas de données en 2022.

Solution : 
- faire des recherches et prendre des precaution lors de possible fusion de données
- recuperer les noms de pays ayant moins de 10 occurrences afin de fusionner les pays ayant changer de noms et garder le nom le plus recent ou donner un nom comme PaysAvant/PaysApres si necessaire.

autre solution: 
- suppression des pays n'ayant pas 10 occurences sans essayer de reunir les données où c'est possible mais pertes de données
- garder les données déséquilibrées mais peut provoquer des problèmes pour des analyses
- mise en place d'un index mais contraigant pour les graphiques
- mise en place d'un modele pour compléter les données mais peut apporter des biais

7. Correction du nombre de pays

Première correction : on garde seulement les 120 pays disponibles sur toutes les années de la décennie

In [18]:
# Filtrer le DataFrame pour ne garder que ces pays
df_filtered = df_combined[df_combined["Country"].isin(countries_all_years)]

# Vérification après filtrage
print(f"Nombre total de lignes après filtrage : {len(df_filtered)}")

output_path = "../data/120pays/120pays_happiness_combined_corrigé.csv"
df_filtered.to_csv(output_path, index=False, encoding="utf-8")
print(f"Fichier final enregistré sous : {output_path}")

Nombre total de lignes après filtrage : 1210
Fichier final enregistré sous : ../data/120pays/120pays_happiness_combined_corrigé.csv